// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: ligato/vpp/lb/lb.proto

package vpp_lb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LBVip_Encap int32

const (
	LBVip_GRE4  LBVip_Encap = 0
	LBVip_GRE6  LBVip_Encap = 1
	LBVip_L3DSR LBVip_Encap = 2
	LBVip_NAT4  LBVip_Encap = 3
	LBVip_NAT6  LBVip_Encap = 4
)

// Enum value maps for LBVip_Encap.
var (
	LBVip_Encap_name = map[int32]string{
		0: "GRE4",
		1: "GRE6",
		2: "L3DSR",
		3: "NAT4",
		4: "NAT6",
	}
	LBVip_Encap_value = map[string]int32{
		"GRE4":  0,
		"GRE6":  1,
		"L3DSR": 2,
		"NAT4":  3,
		"NAT6":  4,
	}
)

func (x LBVip_Encap) Enum() *LBVip_Encap {
	p := new(LBVip_Encap)
	*p = x
	return p
}

func (x LBVip_Encap) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LBVip_Encap) Descriptor() protoreflect.EnumDescriptor {
	return file_ligato_vpp_lb_lb_proto_enumTypes[0].Descriptor()
}

func (LBVip_Encap) Type() protoreflect.EnumType {
	return &file_ligato_vpp_lb_lb_proto_enumTypes[0]
}

func (x LBVip_Encap) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LBVip_Encap.Descriptor instead.
func (LBVip_Encap) EnumDescriptor() ([]byte, []int) {
	return file_ligato_vpp_lb_lb_proto_rawDescGZIP(), []int{1, 0}
}

type LBVip_SrvType int32

const (
	LBVip_CLUSTERIP LBVip_SrvType = 0
	LBVip_NODEPORT  LBVip_SrvType = 1
)

// Enum value maps for LBVip_SrvType.
var (
	LBVip_SrvType_name = map[int32]string{
		0: "CLUSTERIP",
		1: "NODEPORT",
	}
	LBVip_SrvType_value = map[string]int32{
		"CLUSTERIP": 0,
		"NODEPORT":  1,
	}
)

func (x LBVip_SrvType) Enum() *LBVip_SrvType {
	p := new(LBVip_SrvType)
	*p = x
	return p
}

func (x LBVip_SrvType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LBVip_SrvType) Descriptor() protoreflect.EnumDescriptor {
	return file_ligato_vpp_lb_lb_proto_enumTypes[1].Descriptor()
}

func (LBVip_SrvType) Type() protoreflect.EnumType {
	return &file_ligato_vpp_lb_lb_proto_enumTypes[1]
}

func (x LBVip_SrvType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LBVip_SrvType.Descriptor instead.
func (LBVip_SrvType) EnumDescriptor() ([]byte, []int) {
	return file_ligato_vpp_lb_lb_proto_rawDescGZIP(), []int{1, 1}
}

type LBGlobal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip4SrcAddress string `protobuf:"bytes,1,opt,name=ip4_src_address,json=ip4SrcAddress,proto3" json:"ip4_src_address,omitempty"`
	Ip6SrcAddress string `protobuf:"bytes,2,opt,name=ip6_src_address,json=ip6SrcAddress,proto3" json:"ip6_src_address,omitempty"`
	Bucket        uint32 `protobuf:"varint,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Timeout       uint32 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *LBGlobal) Reset() {
	*x = LBGlobal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ligato_vpp_lb_lb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LBGlobal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBGlobal) ProtoMessage() {}

func (x *LBGlobal) ProtoReflect() protoreflect.Message {
	mi := &file_ligato_vpp_lb_lb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBGlobal.ProtoReflect.Descriptor instead.
func (*LBGlobal) Descriptor() ([]byte, []int) {
	return file_ligato_vpp_lb_lb_proto_rawDescGZIP(), []int{0}
}

func (x *LBGlobal) GetIp4SrcAddress() string {
	if x != nil {
		return x.Ip4SrcAddress
	}
	return ""
}

func (x *LBGlobal) GetIp6SrcAddress() string {
	if x != nil {
		return x.Ip6SrcAddress
	}
	return ""
}

func (x *LBGlobal) GetBucket() uint32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

func (x *LBGlobal) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type LBVip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix     string        `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Protocol   uint32        `protobuf:"varint,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port       uint32        `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Encap      LBVip_Encap   `protobuf:"varint,4,opt,name=encap,proto3,enum=ligato.vpp.lb.LBVip_Encap" json:"encap,omitempty"`
	Dscp       uint32        `protobuf:"varint,5,opt,name=dscp,proto3" json:"dscp,omitempty"`
	SrvType    LBVip_SrvType `protobuf:"varint,6,opt,name=srv_type,json=srvType,proto3,enum=ligato.vpp.lb.LBVip_SrvType" json:"srv_type,omitempty"`
	TargetPort uint32        `protobuf:"varint,7,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	NodePort   uint32        `protobuf:"varint,8,opt,name=node_port,json=nodePort,proto3" json:"node_port,omitempty"`
	NewLen     uint32        `protobuf:"varint,9,opt,name=new_len,json=newLen,proto3" json:"new_len,omitempty"`
}

func (x *LBVip) Reset() {
	*x = LBVip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ligato_vpp_lb_lb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LBVip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBVip) ProtoMessage() {}

func (x *LBVip) ProtoReflect() protoreflect.Message {
	mi := &file_ligato_vpp_lb_lb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBVip.ProtoReflect.Descriptor instead.
func (*LBVip) Descriptor() ([]byte, []int) {
	return file_ligato_vpp_lb_lb_proto_rawDescGZIP(), []int{1}
}

func (x *LBVip) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *LBVip) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *LBVip) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *LBVip) GetEncap() LBVip_Encap {
	if x != nil {
		return x.Encap
	}
	return LBVip_GRE4
}

func (x *LBVip) GetDscp() uint32 {
	if x != nil {
		return x.Dscp
	}
	return 0
}

func (x *LBVip) GetSrvType() LBVip_SrvType {
	if x != nil {
		return x.SrvType
	}
	return LBVip_CLUSTERIP
}

func (x *LBVip) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *LBVip) GetNodePort() uint32 {
	if x != nil {
		return x.NodePort
	}
	return 0
}

func (x *LBVip) GetNewLen() uint32 {
	if x != nil {
		return x.NewLen
	}
	return 0
}

type LBAs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix   string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Protocol uint32 `protobuf:"varint,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port     uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Address  string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *LBAs) Reset() {
	*x = LBAs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ligato_vpp_lb_lb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LBAs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBAs) ProtoMessage() {}

func (x *LBAs) ProtoReflect() protoreflect.Message {
	mi := &file_ligato_vpp_lb_lb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBAs.ProtoReflect.Descriptor instead.
func (*LBAs) Descriptor() ([]byte, []int) {
	return file_ligato_vpp_lb_lb_proto_rawDescGZIP(), []int{2}
}

func (x *LBAs) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *LBAs) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *LBAs) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *LBAs) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_ligato_vpp_lb_lb_proto protoreflect.FileDescriptor

var file_ligato_vpp_lb_lb_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2f, 0x76, 0x70, 0x70, 0x2f, 0x6c, 0x62, 0x2f,
	0x6c, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f,
	0x2e, 0x76, 0x70, 0x70, 0x2e, 0x6c, 0x62, 0x22, 0x8c, 0x01, 0x0a, 0x08, 0x4c, 0x42, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x70, 0x34, 0x5f, 0x73, 0x72, 0x63, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69,
	0x70, 0x34, 0x53, 0x72, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x0f,
	0x69, 0x70, 0x36, 0x5f, 0x73, 0x72, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x70, 0x36, 0x53, 0x72, 0x63, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x8b, 0x03, 0x0a, 0x05, 0x4c, 0x42, 0x56, 0x69, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x65, 0x6e, 0x63, 0x61,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f,
	0x2e, 0x76, 0x70, 0x70, 0x2e, 0x6c, 0x62, 0x2e, 0x4c, 0x42, 0x56, 0x69, 0x70, 0x2e, 0x45, 0x6e,
	0x63, 0x61, 0x70, 0x52, 0x05, 0x65, 0x6e, 0x63, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x73,
	0x63, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x64, 0x73, 0x63, 0x70, 0x12, 0x38,
	0x0a, 0x08, 0x73, 0x72, 0x76, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2e, 0x76, 0x70, 0x70, 0x2e, 0x6c, 0x62,
	0x2e, 0x4c, 0x42, 0x56, 0x69, 0x70, 0x2e, 0x53, 0x72, 0x76, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x73, 0x72, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x6f,
	0x64, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x5f, 0x6c, 0x65,
	0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x65, 0x77, 0x4c, 0x65, 0x6e, 0x22,
	0x3a, 0x0a, 0x05, 0x45, 0x6e, 0x63, 0x61, 0x70, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x52, 0x45, 0x34,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x52, 0x45, 0x36, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x4c, 0x33, 0x44, 0x53, 0x52, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x41, 0x54, 0x34, 0x10,
	0x03, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x41, 0x54, 0x36, 0x10, 0x04, 0x22, 0x27, 0x0a, 0x08, 0x53,
	0x72, 0x76, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4c, 0x55, 0x53, 0x54,
	0x45, 0x52, 0x49, 0x50, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x44, 0x45, 0x50, 0x4f,
	0x52, 0x54, 0x10, 0x01, 0x22, 0x68, 0x0a, 0x04, 0x4c, 0x42, 0x41, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x36,
	0x5a, 0x34, 0x67, 0x6f, 0x2e, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2e, 0x69, 0x6f, 0x2f, 0x76,
	0x70, 0x70, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2f, 0x76, 0x70, 0x70, 0x2f, 0x6c, 0x62, 0x3b,
	0x76, 0x70, 0x70, 0x5f, 0x6c, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ligato_vpp_lb_lb_proto_rawDescOnce sync.Once
	file_ligato_vpp_lb_lb_proto_rawDescData = file_ligato_vpp_lb_lb_proto_rawDesc
)

func file_ligato_vpp_lb_lb_proto_rawDescGZIP() []byte {
	file_ligato_vpp_lb_lb_proto_rawDescOnce.Do(func() {
		file_ligato_vpp_lb_lb_proto_rawDescData = protoimpl.X.CompressGZIP(file_ligato_vpp_lb_lb_proto_rawDescData)
	})
	return file_ligato_vpp_lb_lb_proto_rawDescData
}

var file_ligato_vpp_lb_lb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ligato_vpp_lb_lb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ligato_vpp_lb_lb_proto_goTypes = []interface{}{
	(LBVip_Encap)(0),   // 0: ligato.vpp.lb.LBVip.Encap
	(LBVip_SrvType)(0), // 1: ligato.vpp.lb.LBVip.Srv_type
	(*LBGlobal)(nil),   // 2: ligato.vpp.lb.LBGlobal
	(*LBVip)(nil),      // 3: ligato.vpp.lb.LBVip
	(*LBAs)(nil),       // 4: ligato.vpp.lb.LBAs
}
var file_ligato_vpp_lb_lb_proto_depIdxs = []int32{
	0, // 0: ligato.vpp.lb.LBVip.encap:type_name -> ligato.vpp.lb.LBVip.Encap
	1, // 1: ligato.vpp.lb.LBVip.srv_type:type_name -> ligato.vpp.lb.LBVip.Srv_type
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ligato_vpp_lb_lb_proto_init() }
func file_ligato_vpp_lb_lb_proto_init() {
	if File_ligato_vpp_lb_lb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ligato_vpp_lb_lb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LBGlobal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ligato_vpp_lb_lb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LBVip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ligato_vpp_lb_lb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LBAs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ligato_vpp_lb_lb_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ligato_vpp_lb_lb_proto_goTypes,
		DependencyIndexes: file_ligato_vpp_lb_lb_proto_depIdxs,
		EnumInfos:         file_ligato_vpp_lb_lb_proto_enumTypes,
		MessageInfos:      file_ligato_vpp_lb_lb_proto_msgTypes,
	}.Build()
	File_ligato_vpp_lb_lb_proto = out.File
	file_ligato_vpp_lb_lb_proto_rawDesc = nil
	file_ligato_vpp_lb_lb_proto_goTypes = nil
	file_ligato_vpp_lb_lb_proto_depIdxs = nil
}
